"""Michi Ecosystem constants — status strings and issue codes."""

STATUS_OK = "ok"
STATUS_WARNING = "warning"
STATUS_ERROR = "error"
STATUS_UNKNOWN = "unknown"
STATUS_DISABLED = "disabled"
STATUS_NOT_CONFIGURED = "not_configured"
STATUS_UNREACHABLE = "unreachable"
STATUS_REQUIRES_PAIRING = "requires_pairing"
STATUS_CONNECTED = "connected"
STATUS_CONFIGURED = "configured"
STATUS_PARTIAL = "partial"
STATUS_PAIRED = "paired"
STATUS_SYNCING = "syncing"
STATUS_STOPPED = "stopped"
STATUS_NO_DEVICE = "no_device"

MICRO_NOT_CONFIGURED = "MICRO_NOT_CONFIGURED"
MICRO_UNREACHABLE = "MICRO_UNREACHABLE"
MICRO_REQUIRES_PAIRING = "MICRO_REQUIRES_PAIRING"
MICRO_CONTRACT_ERROR = "MICRO_CONTRACT_ERROR"
MICRO_CONTRACT_MISMATCH = "MICRO_CONTRACT_MISMATCH"
MICRO_IMPORT_UNAVAILABLE = "MICRO_IMPORT_UNAVAILABLE"
MICRO_QUEUE_TRANSFER_UNAVAILABLE = "MICRO_QUEUE_TRANSFER_UNAVAILABLE"

SYNC_DISABLED = "SYNC_DISABLED"
SYNC_STOPPED = "SYNC_STOPPED"
NO_PAIRED_DEVICES = "NO_PAIRED_DEVICES"
MOBILE_PAIRING_REQUIRED = "MOBILE_PAIRING_REQUIRED"
MOBILE_SYNC_ERROR = "MOBILE_SYNC_ERROR"

HOME_AUDIO_DISABLED = "HOME_AUDIO_DISABLED"
HOME_AUDIO_PARTIAL = "HOME_AUDIO_PARTIAL"
HOME_AUDIO_MISSING_HA_URL = "HOME_AUDIO_MISSING_HA_URL"
MICHILINK_API_DISABLED = "MICHILINK_API_DISABLED"

REMOTE_SERVER_CONFIGURED = "REMOTE_SERVER_CONFIGURED"
REMOTE_SERVER_NOT_CONFIGURED = "REMOTE_SERVER_NOT_CONFIGURED"

UNKNOWN_ERROR = "UNKNOWN_ERROR"


def overall_from_statuses(statuses: list[str]) -> str:
    if STATUS_ERROR in statuses:
        return STATUS_ERROR
    if STATUS_WARNING in statuses or STATUS_UNREACHABLE in statuses or STATUS_REQUIRES_PAIRING in statuses:
        return STATUS_WARNING
    if any(s in (STATUS_OK, STATUS_CONNECTED, STATUS_CONFIGURED, STATUS_PAIRED, STATUS_SYNCING) for s in statuses):
        return STATUS_OK
    return STATUS_UNKNOWN
