"""Event types for the context system — internal, serializable events."""


class AppEvent:
    APP_STARTED = "app_started"
    APP_CLOSED = "app_closed"
    SECTION_CHANGED = "section_changed"
    LIBRARY_TAB_CHANGED = "library_tab_changed"
    TRACK_SELECTED = "track_selected"
    TRACK_PLAYED = "track_played"
    TRACK_PAUSED = "track_paused"
    TRACK_FAVORITED = "track_favorited"
    TRACK_UNFAVORITED = "track_unfavorited"
    SCAN_STARTED = "scan_started"
    SCAN_FINISHED = "scan_finished"
    METADATA_REPAIR_STARTED = "metadata_repair_started"
    METADATA_REPAIR_FINISHED = "metadata_repair_finished"
    AUDIO_ANALYSIS_FINISHED = "audio_analysis_finished"
    MIX_PREVIEW_GENERATED = "mix_preview_generated"
    DEVICE_CONNECTED = "device_connected"
    DEVICE_DISCONNECTED = "device_disconnected"
    SYNC_STARTED = "sync_started"
    SYNC_FINISHED = "sync_finished"
    ASSISTANT_OPENED = "assistant_opened"
    ASSISTANT_ACTION_CONFIRMED = "assistant_action_confirmed"
